name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.0.3
          - ruby: 3.1.0
          - ruby: ruby-head
          - ruby: jruby-head
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: none
    - name: Install Bundler
      run: gem install bundler --no-document --force
    - name: Install gems
      run: bundle install --jobs 4
    - run: unset JRUBY_OPTS
    - name: Run rake
      run: bundle exec rake
